AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for Vibe Dating App frontend assets'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev/staging/prod)
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  DeploymentUUID:
    Type: String
    Description: Unique identifier for deployment tracking

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'vibe-frontend-${Environment}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: hosting
        - Key: DeploymentUUID
          Value: !Ref DeploymentUUID

Outputs:
  FrontendBucketName:
    Description: Name of the S3 bucket for frontend assets
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketName'

  FrontendBucketArn:
    Description: ARN of the S3 bucket for frontend assets
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketArn'

  FrontendBucketDomainName:
    Description: Domain name of the S3 bucket
    Value: !GetAtt FrontendBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketDomainName' 