AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for Vibe Dating App frontend assets'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev/staging/prod)
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  DeploymentUUID:
    Type: String
    Description: Unique identifier for deployment tracking

  CloudFrontDistributionArn:
    Type: String
    Description: ARN of the CloudFront distribution that should have access to this bucket
    Default: ""

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'vibe-frontend-${Environment}-${DeploymentUUID}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: hosting
        - Key: DeploymentUUID
          Value: !Ref DeploymentUUID

  # Bucket Policy for CloudFront Access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: HasCloudFrontDistribution
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${FrontendBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Ref CloudFrontDistributionArn

Conditions:
  HasCloudFrontDistribution: !Not [!Equals [!Ref CloudFrontDistributionArn, ""]]

Outputs:
  FrontendBucketName:
    Description: Name of the S3 bucket for frontend assets
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketName'

  FrontendBucketArn:
    Description: ARN of the S3 bucket for frontend assets
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketArn'

  FrontendBucketDomainName:
    Description: Domain name of the S3 bucket
    Value: !GetAtt FrontendBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketDomainName' 