AWSTemplateFormatVersion: '2010-09-09'
Description: 'Vibe Dating - Frontend-Hosting S3 Resources Infrastructure'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (dev/staging/prod)
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  Region:
    Type: String
    Description: Region for the application (e.g., us-east-1)

  DeploymentUUID:
    Type: String
    Description: Unique identifier for deployment tracking

  AppBucketName:
    Type: String
    Description: Name of the S3 bucket containing frontend assets

  CloudFrontDistributionArn:
    Type: String
    Description: ARN of the CloudFront distribution that should have access to this bucket
    Default: ""

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: hosting
        - Key: DeploymentUUID
          Value: !Ref DeploymentUUID

  # Bucket Policy for CloudFront Access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Join ['', [!GetAtt FrontendBucket.Arn, '/*']]
            Condition:
              StringEquals:
                AWS:SourceArn: !Ref CloudFrontDistributionArn

Outputs:
  AppBucketArn:
    Description: ARN of the S3 bucket for frontend assets
    Value: !GetAtt FrontendBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketArn'

  AppBucketDomainName:
    Description: Domain name of the S3 bucket
    Value: !GetAtt FrontendBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucketDomainName' 