AWSTemplateFormatVersion: '2010-09-09'
Description: 'Vibe Dating - Core-Service DynamoDB Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # KMS Key for DynamoDB encryption
  DynamoDBKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for Vibe Dating DynamoDB table encryption - ${Environment}'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow DynamoDB to use the key
            Effect: Allow
            Principal:
              Service: dynamodb.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth

  DynamoDBKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/vibe-dating-dynamodb-${Environment}'
      TargetKeyId: !Ref DynamoDBKMSKey

  # DynamoDB Table
  VibeDatingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'vibe-dating-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
        - AttributeName: GSI2PK
          AttributeType: S
        - AttributeName: GSI2SK
          AttributeType: S
        - AttributeName: GSI3PK
          AttributeType: S
        - AttributeName: GSI3SK
          AttributeType: S
        - AttributeName: GSI4PK
          AttributeType: S
        - AttributeName: GSI4SK
          AttributeType: S
        - AttributeName: GSI5PK
          AttributeType: S
        - AttributeName: GSI5SK
          AttributeType: S
        - AttributeName: GSI6PK
          AttributeType: S
        - AttributeName: GSI6SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2PK
              KeyType: HASH
            - AttributeName: GSI2SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI3
          KeySchema:
            - AttributeName: GSI3PK
              KeyType: HASH
            - AttributeName: GSI3SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI4
          KeySchema:
            - AttributeName: GSI4PK
              KeyType: HASH
            - AttributeName: GSI4SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI5
          KeySchema:
            - AttributeName: GSI5PK
              KeyType: HASH
            - AttributeName: GSI5SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI6
          KeySchema:
            - AttributeName: GSI6PK
              KeyType: HASH
            - AttributeName: GSI6SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref DynamoDBKMSKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth

Outputs:
  DynamoDBTableName:
    Description: 'DynamoDB Table Name'
    Value: !Ref VibeDatingTable
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBTableName'

  # DynamoDBTableArn:
  #   Description: 'DynamoDB Table ARN'
  #   Value: !GetAtt VibeDatingTable.Arn
  #   Export:
  #     Name: !Sub '${AWS::StackName}-DynamoDBTableArn'

  # DynamoDBKMSKeyArn:
  #   Description: 'DynamoDB KMS Key ARN'
  #   Value: !GetAtt DynamoDBKMSKey.Arn
  #   Export:
  #     Name: !Sub '${AWS::StackName}-DynamoDBKMSKeyArn'
  DynamoDBKMSKeyArn:
    Value: !GetAtt DynamoDBKMSKey.Arn
  DynamoDBTableArn:
    Value: !GetAtt VibeDatingTable.Arn

  DynamoDBKMSKeyAliasName:
    Description: 'DynamoDB KMS Key Alias Name'
    Value: !Ref DynamoDBKMSKeyAlias
    Export:
      Name: !Sub '${AWS::StackName}-DynamoDBKMSKeyAliasName' 