# General
Environment: "dev"
Region: "il-central-1"
DeploymentUUID: "8e64f92e-580e-11f0-80ef-00155d453b17"

# App
AppDomainName: "tma.vibe-dating.io"
AppAllowedOrigins: "https://web.telegram.org,https://t.me,https://shlomosh.github.io,https://tma.vibe-dating.io"
AppCertificateArn: "arn:aws:acm:us-east-1:555171060142:certificate/faa3b179-b4c8-426c-a9a3-c5f0536bba62"

# Api
ApiDomainName: "api.vibe-dating.io"
ApiHostedZoneId: "Z02615543R07F6C5EKHGP"
ApiCertificateArn: "arn:aws:acm:il-central-1:555171060142:certificate/1cbb4fee-9528-45c5-949d-e0b658013ce4"
