AWSTemplateFormatVersion: '2010-09-09'
Description: 'Vibe Dating - Auth-Service Lambda Resources Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  LambdaCodeBucketName:
    Type: String
    Description: Lambda Code Bucket Name (imported from s3 stack)

  LambdaExecutionRoleArn:
    Type: String
    Description: Lambda Execution Role ARN (imported from iam stack)

Resources:
  # Lambda Layer for shared dependencies
  AuthLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub 'vibe-auth-layer-${Environment}'
      Description: 'Vibe Dating App base layer with shared dependencies'
      Content:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: lambda/auth_layer.zip
      CompatibleRuntimes:
        - python3.11
      CompatibleArchitectures:
        - x86_64
      # Tags:
      #   - Key: Environment
      #     Value: !Ref Environment
      #   - Key: Service
      #     Value: auth

  # Lambda function for platform authentication
  PlatformAuthFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'vibe-platform-auth-${Environment}'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: lambda/platform_auth.zip
      Layers:
        - !Ref AuthLayer
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN_SECRET_ARN: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:vibe-dating/telegram-bot-token/${Environment}'
          JWT_SECRET_ARN: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:vibe-dating/jwt-secret/${Environment}'
          UUID_NAMESPACE_SECRET_ARN: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:vibe-dating/uuid-namespace/${Environment}'
      Timeout: 30
      MemorySize: 256
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth

  # Lambda function for JWT authorization
  UserJWTAuthorizerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'vibe-user-jwt-authorizer-${Environment}'
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        S3Bucket: !Ref LambdaCodeBucketName
        S3Key: lambda/user_jwt_authorizer.zip
      Layers:
        - !Ref AuthLayer
      Environment:
        Variables:
          JWT_SECRET_ARN: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:vibe-dating/jwt-secret/${Environment}'
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth

  # CloudWatch Log Group for Lambda functions
  PlatformAuthLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/vibe-platform-auth-${Environment}'
      RetentionInDays: 14

  UserJWTAuthorizerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/vibe-user-jwt-authorizer-${Environment}'
      RetentionInDays: 14

Outputs:
  PlatformAuthFunctionArn:
    Description: 'Platform Auth Lambda Function ARN'
    Value: !GetAtt PlatformAuthFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PlatformAuthFunctionArn'

  UserJWTAuthorizerFunctionArn:
    Description: 'JWT Authorizer Lambda Function ARN'
    Value: !GetAtt UserJWTAuthorizerFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserJWTAuthorizerFunctionArn'

  AuthLayerArn:
    Description: 'Vibe Base Layer ARN'
    Value: !Ref AuthLayer
    Export:
      Name: !Sub '${AWS::StackName}-AuthLayerArn'

  PlatformAuthFunctionName:
    Description: 'Platform Auth Lambda Function Name'
    Value: !Ref PlatformAuthFunction
    Export:
      Name: !Sub '${AWS::StackName}-PlatformAuthFunctionName'

  UserJWTAuthorizerFunctionName:
    Description: 'JWT Authorizer Lambda Function Name'
    Value: !Ref UserJWTAuthorizerFunction
    Export:
      Name: !Sub '${AWS::StackName}-UserJWTAuthorizerFunctionName' 