AWSTemplateFormatVersion: '2010-09-09'
Description: 'Vibe Dating - Auth-Service API Gateway Resources Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name

  ApiDomainName:
    Type: String
    Default: api.vibe-dating.io
    Description: Domain name for the API Gateway

  AllowedOrigins:
    Type: String
    Default: "https://web.telegram.org,https://t.me,https://shlomosh.github.io,https://tma.vibe-dating.io"
    Description: Allowed CORS origins

  UserJWTAuthorizerFunctionArn:
    Type: String
    Description: JWT Authorizer Lambda Function ARN (imported from lambda stack)

  ApiGatewayAuthorizerRoleArn:
    Type: String
    Description: API Gateway Authorizer Role ARN (imported from iam stack)

  PlatformAuthFunctionArn:
    Type: String
    Description: Platform Auth Lambda Function ARN (imported from lambda stack)

  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for the custom domain
    Default: "arn:aws:acm:il-central-1:555171060142:certificate/1cbb4fee-9528-45c5-949d-e0b658013ce4"

  HostedZoneId:
    Type: String
    Description: Route 53 Hosted Zone ID for the domain
    Default: "Z02615543R07F6C5EKHGP"

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub 'vibe-api-${Environment}'
      Description: 'Vibe Dating App API Gateway'
      EndpointConfiguration:
        Types:
          - REGIONAL
      BinaryMediaTypes:
        - '*/*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth

  # Custom Domain Name
  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Condition: HasCertificate
    Properties:
      DomainName: !Ref ApiDomainName
      RegionalCertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL
      SecurityPolicy: TLS_1_2
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Service
          Value: auth
        - Key: Domain
          Value: !Ref ApiDomainName

  # Base Path Mapping
  ApiGatewayBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: HasCertificate
    Properties:
      DomainName: !Ref ApiGatewayDomainName
      RestApiId: !Ref ApiGateway
      Stage: !Ref Environment
      BasePath: ""

  # Route 53 A Record (Alias)
  ApiGatewayAliasRecord:
    Type: AWS::Route53::RecordSet
    Condition: HasCertificate
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApiDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt ApiGatewayDomainName.RegionalDomainName
        HostedZoneId: !GetAtt ApiGatewayDomainName.RegionalHostedZoneId

  # API Gateway Authorizer
  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: !Sub 'vibe-user-jwt-authorizer-${Environment}'
      Type: TOKEN
      RestApiId: !Ref ApiGateway
      AuthorizerUri: !Sub 
        - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
        - LambdaArn: !Ref UserJWTAuthorizerFunctionArn
      AuthorizerCredentials: !Ref ApiGatewayAuthorizerRoleArn
      AuthorizerResultTtlInSeconds: 300
      IdentitySource: method.request.header.Authorization

  # Lambda permission for API Gateway to invoke authorizer
  AuthorizerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UserJWTAuthorizerFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  # API Gateway Resources and Methods
  AuthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: auth

  PlatformAuthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref AuthResource
      PathPart: platform

  PlatformAuthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref PlatformAuthResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !Ref PlatformAuthFunctionArn
      RequestParameters:
        method.request.header.Content-Type: true
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
        - StatusCode: '400'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: '401'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
        - StatusCode: '500'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # Lambda permission for API Gateway to invoke platform auth function
  PlatformAuthLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PlatformAuthFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*'

  # OPTIONS method for CORS
  PlatformAuthOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref PlatformAuthResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: '200'
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: !Sub "'${AllowedOrigins}'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
              method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
            ResponseTemplates:
              application/json: ''
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Credentials: true

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PlatformAuthMethod
      - PlatformAuthOptionsMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref Environment

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, ""]]

Outputs:
  ApiGatewayUrl:
    Description: 'API Gateway URL'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayUrl'

  ApiGatewayId:
    Description: 'API Gateway ID'
    Value: !Ref ApiGateway
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayId'

  ApiGatewayAuthorizerId:
    Description: 'API Gateway Authorizer ID'
    Value: !Ref ApiGatewayAuthorizer
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayAuthorizerId'

  ApiGatewayRootResourceId:
    Description: 'API Gateway Root Resource ID'
    Value: !GetAtt ApiGateway.RootResourceId
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayRootResourceId'

  CustomDomainUrl:
    Description: 'Custom Domain URL'
    Condition: HasCertificate
    Value: !Sub 'https://${ApiDomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-CustomDomainUrl'

  ApiGatewayDomainNameId:
    Description: 'API Gateway Domain Name ID'
    Condition: HasCertificate
    Value: !Ref ApiGatewayDomainName
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayDomainNameId'

  ApiGatewayDomainNameRegionalDomainName:
    Description: 'API Gateway Domain Name Regional Domain Name'
    Condition: HasCertificate
    Value: !GetAtt ApiGatewayDomainName.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayDomainNameRegionalDomainName' 